import { defineConfig } from 'vite'
import wasm from 'vite-plugin-wasm'
import { OWNER } from './src/data/projects.js'

const SITE = String(OWNER.site ?? '').replace(/\/+$/, '')

// Share cards need absolute URLs — LinkedIn, Twitter/X, Slack and WhatsApp all
// drop a relative og:image — but the build uses a relative base so it can be
// hosted from a project subpath. Those two cannot both be satisfied by one
// static tag, so the absolute ones are injected here from the single
// OWNER.site value rather than hardcoded into a second file.
//
// classic.html carries its own, generated by build-classic.mjs from the same
// constant, so this only touches index.html.
function shareTags() {
  const tags = [
    `<meta property="og:url" content="${SITE}/">`,
    `<meta property="og:image" content="${SITE}/og.png">`,
    `<meta property="og:image:width" content="1200">`,
    `<meta property="og:image:height" content="630">`,
    `<meta name="twitter:image" content="${SITE}/og.png">`,
    `<link rel="canonical" href="${SITE}/">`,
  ]
  const block = tags.map((t) => `  ${t}`).join('\n')

  return {
    name: 'share-tags',
    transformIndexHtml: {
      order: 'pre',
      handler(html, ctx) {
        if (!ctx.filename.endsWith('index.html')) return html
        return html.replace('</head>', `${block}\n</head>`)
      },
    },
  }
}

export default defineConfig({
  // @dimforge/rapier3d imports its .wasm via WASM-ESM integration, which needs
  // this transform. Top-level await is fine without a second plugin because the
  // build targets es2022.
  plugins: [wasm(), shareTags()],
  // Relative base so the build works from a GitHub Pages project subpath too.
  base: './',
  build: {
    target: 'es2022',
    outDir: 'dist',
    assetsInlineLimit: 0,
    rollupOptions: {
      // Two entries: the showroom, and the generated fallback/CV page.
      input: {
        main: 'index.html',
        classic: 'classic.html',
      },
    },
  },
  server: { port: 5173 },
})
