import { defineConfig } from 'vite'
import wasm from 'vite-plugin-wasm'
import { OWNER, OG_IMAGE } from './src/data/projects.js'

const SITE = String(OWNER.site ?? '').replace(/\/+$/, '')

const esc = (s) => String(s ?? '').replace(/[&<>"']/g, (c) => (
  { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]
))

// Everything in index.html's <head> that is really a fact about the owner.
//
// Two separate reasons these are injected rather than written into the file:
//
//  - The URLs MUST be absolute. LinkedIn, Twitter/X, Slack and WhatsApp all drop
//    a relative og:image, and the sitemap spec rejects a relative <loc> — but
//    the build uses a relative `base` so it can be hosted from a project
//    subpath. One static tag cannot be both.
//  - The title and description were the LAST copies of OWNER.title left
//    hardcoded anywhere. index.html said "Unity Game Developer" while
//    classic.html derived "Senior Unity Developer" from the constant, so the two
//    routes of the same site introduced their owner differently. This is the
//    same fix the URLs already got: one constant, every output.
//
// classic.html carries its own equivalents, generated by build-classic.mjs from
// these same constants, so this only touches index.html.
function headTags() {
  const title = `${OWNER.name} — ${OWNER.title}`
  const description =
    `An explorable 3D showroom of Unity, XR and digital-twin work by ${OWNER.name}, ` +
    `${OWNER.title} in ${OWNER.location}.`
  const shareDescription =
    'Walk through an interactive showroom of shipped games, XR training and ' +
    `digital-twin projects. ${OWNER.tagline}`

  const tags = [
    `<title>${esc(title)}</title>`,
    `<meta name="description" content="${esc(description)}">`,
    `<meta property="og:title" content="${esc(title)}">`,
    `<meta property="og:description" content="${esc(shareDescription)}">`,
    `<meta property="og:url" content="${SITE}/">`,
    `<meta property="og:image" content="${SITE}/${OG_IMAGE.path}">`,
    // The ACTUAL pixels of the file, not the logical size it was posed at.
    `<meta property="og:image:width" content="${OG_IMAGE.width}">`,
    `<meta property="og:image:height" content="${OG_IMAGE.height}">`,
    `<meta name="twitter:image" content="${SITE}/${OG_IMAGE.path}">`,
    `<link rel="canonical" href="${SITE}/">`,
  ]
  const block = tags.map((t) => `  ${t}`).join('\n')

  // The one link in the body that is also owner data. A relative href, because
  // `base` is relative and this file is copied straight out of public/.
  const cvLink = OWNER.cv
    ? `<a class="controls__btn" href="./${esc(OWNER.cv)}" target="_blank" rel="noopener noreferrer">CV (PDF)</a>`
    : ''

  // The front door names its owner. Injected for the same reason the <title>
  // is — one constant, every output — rather than typed into the markup, which
  // is exactly how index.html came to say "Unity Game Developer" while
  // classic.html said "Senior Unity Developer".
  const ownerName = esc(OWNER.name)
  const ownerTitle = esc(OWNER.title)

  return {
    name: 'head-tags',
    transformIndexHtml: {
      order: 'pre',
      handler(html, ctx) {
        if (!ctx.filename.endsWith('index.html')) return html
        return html
          .replace('</head>', `${block}\n</head>`)
          .replace('<!--CV_LINK-->', cvLink)
          .replace('<!--OWNER_NAME-->', ownerName)
          .replace('<!--OWNER_TITLE-->', ownerTitle)
      },
    },
  }
}

export default defineConfig({
  // @dimforge/rapier3d imports its .wasm via WASM-ESM integration, which needs
  // this transform. Top-level await is fine without a second plugin because the
  // build targets es2022.
  plugins: [wasm(), headTags()],
  // Relative base so the build works from a GitHub Pages project subpath too.
  base: './',
  build: {
    target: 'es2022',
    outDir: 'dist',
    assetsInlineLimit: 0,
    rollupOptions: {
      // Two entries: the showroom, and the generated fallback/CV page.
      input: {
        main: 'index.html',
        classic: 'classic.html',
      },
    },
  },
  server: { port: 5173 },
})
