import { defineConfig } from 'vite'
import { OWNER, OG_IMAGE } from './src/data/projects.js'
import { ROUTE_NAMES, DOOR_SKIP_PARAMS } from './src/core/params.js'
import { levelMarkup, doorMarkup, esc } from './src/level/markup.js'

const SITE = String(OWNER.site ?? '').replace(/\/+$/, '')

// Everything in index.html that is really a fact about the owner or the data.
//
//  - The URLs MUST be absolute. LinkedIn, Twitter/X, Slack and WhatsApp all drop
//    a relative og:image, and the sitemap spec rejects a relative <loc> — but
//    the build uses a relative `base` so it can be hosted from a project
//    subpath. One static tag cannot be both.
//  - The title and description come from OWNER, so the two routes introduce
//    their owner the same way.
//  - The level itself is generated from src/data, so adding a project is one
//    object in projects.js and it appears on the page as a platform.
//
// classic.html carries its own equivalents, generated by build-classic.mjs from
// these same constants, so this only touches index.html.
function headTags() {
  const title = `${OWNER.name} — ${OWNER.title}`
  const description =
    `A portfolio you play through: the Unity, XR and digital-twin work of ${OWNER.name}, ` +
    `${OWNER.title} in ${OWNER.location}, as a platformer built from the page itself.`
  const shareDescription =
    'Jump down a page of shipped games, XR training and digital-twin projects. ' +
    OWNER.tagline

  const tags = [
    `<title>${esc(title)}</title>`,
    `<meta name="description" content="${esc(description)}">`,
    `<meta property="og:title" content="${esc(title)}">`,
    `<meta property="og:description" content="${esc(shareDescription)}">`,
    `<meta property="og:url" content="${SITE}/">`,
    `<meta property="og:image" content="${SITE}/${OG_IMAGE.path}">`,
    // The ACTUAL pixels of the file, not the logical size it was posed at.
    `<meta property="og:image:width" content="${OG_IMAGE.width}">`,
    `<meta property="og:image:height" content="${OG_IMAGE.height}">`,
    `<meta name="twitter:image" content="${SITE}/${OG_IMAGE.path}">`,
    `<link rel="canonical" href="${SITE}/">`,
  ]
  const block = tags.map((t) => `  ${t}`).join('\n')

  // A relative href, because `base` is relative and the file is copied straight
  // out of public/.
  const cvLink = OWNER.cv
    ? `<a class="controls__btn" href="./${esc(OWNER.cv)}" target="_blank" rel="noopener noreferrer">CV (PDF)</a>`
    : ''

  // Whether to ask which portfolio, decided before first paint so the door never
  // flashes up over a level that was already chosen. The parameters that skip
  // it come from params.js, so this cannot drift from the links that carry them.
  const doorCheck = `<script>(function(){var q=new URLSearchParams(location.search);if(!${JSON.stringify(DOOR_SKIP_PARAMS)}.some(function(k){return q.has(k)}))document.documentElement.classList.add("has-door")})()</script>`

  return {
    name: 'head-tags',
    transformIndexHtml: {
      order: 'pre',
      handler(html, ctx) {
        if (!ctx.filename.endsWith('index.html')) return html
        return html
          .replace('</head>', `${block}\n</head>`)
          .replace('<!--DOOR_CHECK-->', doorCheck)
          .replace('<!--DOOR-->', doorMarkup())
          .replace('<!--LEVEL-->', levelMarkup())
          .replace('<!--CV_LINK-->', cvLink)
          .replace(/<!--LABEL_BASIC-->/g, esc(ROUTE_NAMES.basic))
      },
    },
  }
}

export default defineConfig({
  plugins: [headTags()],
  // Relative base so the build works from a GitHub Pages project subpath too.
  base: './',
  build: {
    target: 'es2022',
    outDir: 'dist',
    assetsInlineLimit: 0,
    rollupOptions: {
      // Two entries: the platformer, and the generated plain page.
      input: {
        main: 'index.html',
        classic: 'classic.html',
      },
    },
  },
  server: { port: 5173 },
})
